### ISSUE TITLE
What happened to bintomon ? 

### ISSUE THREAD

**Issue by xavrr** [dschmenk/apple2pi#16]
Hi there,
Great piece of software !!

What happened to bintomon ?  Can't find reference to it except in the documentation...

**Comment by xavrr** [comment]
hmmm it's apparently part of another set of tools

https://github.com/jefftranter/6502

**Comment by dschmenk** [comment]
No, it's in the share directory: https://github.com/dschmenk/apple2pi/blob/master/share/bintomon.c
