### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by edescourtis** [dschmenk/apple2pi#8]
It's impossible to find the Apple 2 Pi hardware. When can I buy the hardware? Could you give the schematics?

**Comment by dschmenk** [comment]
Although there is new hardware in development, there isn't any ETA for the hardware to be available. However, there are a few other options. One is to use a Super Serial Card connected to a USB <-> serial port dongle that is supported by Linux. You can also build your own using these schematics:
http://schmenk.is-a-geek.com/wordpress/wp-content/uploads/2013/07/apple2pi_schematic.pdf

You can find more information on 
http://schmenk.is-a-geek.com/wordpress
 and 
https://www.ultimateapple2.com/forums/

Thanks for your patience.

**Comment by drkenb** [comment]
Hi David - Not sure why I received the email (below) but just to let you know, the Apple2Online Store sells USB-SuperSerial Card and USB-IIGS/IIcPLUS cables:

https://www.ebluejay.com/Ads/Item/5058024

Ken
drkenb / Apple-2-Online

Visit my sales venues at:
 
☆ Webstore: https://www.ebluejay.com/store/Apple2OnlineStore  - Vintage Apple II Computers

Visit my informational websites at:
 
☆ http://www.Apple2Online.com - the ultimate online resource for the Apple II family of computers!
 
☆ http://CanonPortablePrinters.drkenb.com - the comprehensive online resource for Canon's portable inkjet printers!
 
☆ http://Photography.drkenb.com - Photographic library



________________________________________________________________________


Date: Fri, 4 Dec 2015 21:59:16 -0800
